-- MongoDB replaces the previous MySQL schema.
--
-- Collections used by the backend:
--   qa_data:
--     original_question, norm_question, answer, source, confidence, is_active, created_at
--   pending_questions:
--     question, norm_question, created_at
--
-- The application initializes these collections through Mongoose in
-- Backend/src/db/db.js, so this file is kept only as a migration note.